---
title: Flight Compute Tutorial
short_title: Tutorial
paras:
 - >-
   Get up and running with this simple Alces Flight Compute tutorial
   challenge.
 - >-
   You can <a href="/tutorial">access the tutorial by clicking here</a>.
