#!/bin/bash
#==============================================================================
# Copyright (C) 2017 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action
require handler
require process
require job-queue

main() {
    local queue job_file job_id output_file
    queue="$1"
    job_id="$2"
    output_file="$3"

    if [ -z "${queue}" -o -z "${job_id}" -o -z "${output_file}" ] ; then
        action_die "usage: ${cw_BINNAME} [OPTIONS] <queue> <job_id> <output_file>"
    fi

    job_queue_get_output_file "${queue}" "${job_id}" "${output_file}"
}

process_reexec_sudo "$@"
main "$@"
