#!/bin/bash
#==============================================================================
# Copyright (C) 2017 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action
require handler

main() {
    local queue
    queue="$1"

    if [ -z "${queue}" ] ; then
        action_die "usage: ${cw_BINNAME} <queue>"
    fi

    job_queue_list_jobs_in_queue "${queue}" "pending"
}

if [ -d "${cw_ROOT}"/etc/handlers/cluster-customizer/share ]; then
    handler_add_libdir "${cw_ROOT}"/etc/handlers/cluster-customizer/share
    require job-queue

    main "$@"
else
    action_die 'cluster-customizer handler is not enabled'
fi
