#!/bin/bash
#==============================================================================
# Copyright (C) 2016 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
#ALCES_META
# Refer to `clusterware/scripts/development/propagate`.
#path=/opt/clusterware/libexec/customize/actions/apply
#ALCES_META_END

require action
require handler
require process
require member
require network

process_reexec_sudo "$@"

main() {
  local type profile_name nodes

  if [ "$1" == "-n" ]; then
      nodes="$2"
      shift 2
  fi

  type=${1%%/*}
  profile_name=${1##*/}
  if [[ "$type" == "$profile_name" ]]; then
    echo "Incorrect format for customization profile: $type"
    return 1
  fi

  if [[ "$nodes" ]]; then
    echo $nodes | tr ',' '\n' | while read node; do
      echo "Applying $1 to node $node..."
      ssh $node 'alces handler enable cluster-customizer; alces service install s3cmd; alces customize apply "'$1'"' < /dev/null
    done
  else
    if [[ "$type" == "feature" ]]; then
      customize_apply_feature "$profile_name"
    elif [[ "$type" == "profile" ]]; then
      customize_apply_profile "$profile_name"
    else
      echo "Unknown customization type: $type"
    fi
  fi
}

if [ -d "${cw_ROOT}"/etc/handlers/cluster-customizer/share ]; then
    handler_add_libdir "${cw_ROOT}"/etc/handlers/cluster-customizer/share
    require customize

    if network_has_metadata_service 1; then
        files_load_config cluster-customizer
        cw_CLUSTER_CUSTOMIZER_path="${cw_CLUSTER_CUSTOMIZER_path:-${cw_ROOT}/var/lib/customizer}"
        cw_CLUSTER_CUSTOMIZER_profiles="${cw_CLUSTER_CUSTOMIZER_profiles:-default}"

        main "$@"
    else
        action_die 'unable to apply: no cloud metadata service detected'
    fi
else
    action_die 'cluster-customizer handler is not enabled'
fi
