#!/bin/bash
#==============================================================================
# Copyright (C) 2017 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================

require ruby

ruby_run <<RUBY

require 'yaml'

rootDir = "$1"

profiles = {}

Dir.entries(rootDir).select {|f| !File.directory? f}.each do |profile_name|
  manifest_file = File.expand_path("#{profile_name}/manifest.txt", rootDir)
  tags_file = File.expand_path("#{profile_name}/tags.txt", rootDir)

  if File.exists?(manifest_file)
    profile = {}

    manifest = File.read(manifest_file).split("\n")
    profile['manifest'] = manifest

    if File.exists(tags_file)
      tags = File.read(tags_file).split("\n")
      profile['tags'] = tags
    end

    profiles[profile_name] = profile
  end
end

index = {'profiles' => profiles}

File.open(File.expand_path('index.yml', rootDir), 'w') { |outFile|
  outFile.write index.to_yaml
}
RUBY
