#!/bin/bash
#==============================================================================
# Copyright (C) 2015 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.vars.sh ]; then
            source "${a}"/clusterware/config.vars.sh
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

main() {
    local params
    if [ -f "${cw_ROOT}/etc/qdesktop.rc" ]; then
        . ${cw_ROOT}/etc/qdesktop.rc
    fi

    cw_QDESKTOP_script=${cw_QDESKTOP_script:-${SGE_ROOT}/etc/scripts/qdesktop-session}
    cw_QDESKTOP_queue=${cw_QDESKTOP_queue:-byslot.q}
    cw_QDESKTOP_vmem=${cw_QDESKTOP_vmem:-4G}
    cw_QDESKTOP_rt=${cw_QDESKTOP_rt:-72:0:0}
    cw_QDESKTOP_session_type=${cw_QDESKTOP_session_type:-${1:-default}}

    if [ "${cw_QDESKTOP_log}" ]; then
        params="${params} -o \"${cw_QDESKTOP_log}\""
    fi

    if [ "${cw_QDESKTOP_project}" ]; then
        params="${params} -P ${cw_QDESKTOP_project}"
    fi

    qsub -now yes -q ${cw_QDESKTOP_queue} \
        -l h_rt=${cw_QDESKTOP_rt} \
        -l h_vmem=${cw_QDESKTOP_vmem} \
        $params \
        ${cw_QDESKTOP_script} ${cw_QDESKTOP_session_type}
}

setup

main "$@"
